<?php
    // If there are results, tell user
    if($results){
	echo '</br></br></br></br>There is already a report for this plan';
    }else{
	      $form->setAttribute('action', $this->url('reports', array('action' => 'addnewreport')));
	      $form->setAttribute('name', 'data');
	      $form->setAttribute('id', 'data');
	      $form->setAttribute('enctype', 'multipart/form-data');
	  
	      $form->prepare();
	      echo $this->form()->openTag($form);
	      echo $this->formHidden($form->get('id')->setAttribute('value', $planData[0]['id']));
	      echo $this->formHidden($form->get('status')->setAttribute('value', '0'));
	  
?>
    <div class="col-md-8">
       <div class="table-responsive">
	    <table class="table table-bordered table-striped">
	      <colgroup>
		<col class="col-xs-8">
	
	      </colgroup>
     
	    <div class="bs-example">
	    <table class="table">
	      
	      <h6>Add New Report</h6>
	      <h4><?php echo $planData[0]['unit_id'] . ' - ' . $planData[0]['name'] . ' - ' . $planData[0]['year'];?></h4>
      
	    <div class="controls">
		<div class="panel-group" id="accordion">
		 <div class="panel panel-success">
		  <div class="panel-heading">
		    <h4 class="panel-title">
		      <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
			 Outcomes
		      </a>
		    </h4>
		  </div>
		  <div class="panel-body">
		      <?php $ctr = 0;?>
	      
		      <?php foreach($descriptions as $description) : ?>
			  <?php $ctr++;?>
			   <?php echo($ctr); ?>.<?php echo $description;?>
			  </br>
			  
			  <?php endforeach; ?>
		  </div>
		
		  <div class="panel-heading">
		    <h4 class="panel-title">
		      <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
			 Population assessed
		      </a>
		    </h4>
		  </div>
		  <div id="collapseThree" class="panel-collapse collapse">
		    <div class="panel-body">
		       <?php
		        $elem = $form->get('population');
		        echo $this->formRow($elem);
		       ?>	 
		     </div>
		  </div>
		  <div class="panel-heading">
		    <h4 class="panel-title">
		      <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
			 Results
		      </a>
		    </h4>
		  </div>
		  <div id="collapseFour" class="panel-collapse collapse">
		    <div class="panel-body">
			<?php
			    $elem = $form->get('results');
			    echo $this->formRow($elem);
		       ?>	 
		     </div>
		  </div>
		  <div class="panel-heading">
		    <h4 class="panel-title">
		      <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
			 Conclusion
		      </a>
		    </h4>
		  </div>
		  <div id="collapseFive" class="panel-collapse collapse">
		    <div class="panel-body">
			<?php
			    $elem = $form->get('conclusions');
			    echo $this->formRow($elem);
		       ?>	 
		     </div>
		  </div>
		  <div class="panel-heading">
		    <h4 class="panel-title">
		      <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
			 Actions
		      </a>
		    </h4>
		  </div>
		  <div id="collapseSix" class="panel-collapse collapse">
		    <div class="panel-body">
			<?php
			    $elem = $form->get('actions');
			    echo $this->formRow($elem);
		       ?>	 
		     
		    </div>
		  </div>
		
	      </div>
	      <table>
		<tr><th>File Description</th></tr>
		
		<!-- enter the first upload row -->
		<tr>
		    <td>
			<?php $elem = $form->get('textFileDescription0'); ?>
			<?php echo $this->formInput($elem); ?>
		    </td>
		    <td>
			<?php $elem = $form->get('fileUpload0'); ?>
			<?php echo $this->formFile($elem); ?>
			<?php echo $this->formElementErrors($elem); ?>
		    </td>
	    
		    <td>
			<a href="#" id="removeFile0" name="removeFile0">Remove File</a>
		    </td>
		</tr>
		
		<!-- enter the second upload row -->
		<tr>
		    <td>
			<?php $elem = $form->get('textFileDescription1'); ?>
			<?php echo $this->formInput($elem); ?>
		    </td>
		    <td>
			<?php $elem = $form->get('fileUpload1'); ?>
			<?php echo $this->formFile($elem); ?>
			<?php echo $this->formElementErrors($elem); ?>
		    </td>
	    
		    <td>
			<a href="#" id="removeFile1" name="removeFile1">Remove File</a>
		    </td>
		</tr>
	    </table>
	      </br>
		      
		      </div> <!-- controls -->
		      <input class="btn btn-primary btn-md" onclick="" id="draftButton" value="Save Draft"></input>
		      <input class="btn btn-success btn-md pull-right" onclick="" id="submitButton" value="Submit Report"></input>
		
	    </table>
	</table>
    <?php echo $this->form()->closeTag();?>

  </div><!-- /example -->
<?php
    }
?>