<?php

// Tell user if no results
if(!$results){
    echo '</br></br></br></br>There are no reports associated with this plan';
}else{
    // get form
    $form->setAttribute('action', $this->url('reports', array('action' => 'updateReport')));
    $form->setAttribute('name', 'data');
    $form->setAttribute('id', 'data');
    $form->setAttribute('enctype', 'multipart/form-data');

    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id')->setAttribute('value', $report[0]['id']));
    echo $this->formHidden($form->get('status')->setAttribute('value', '0'));

?>
<div class="col-md-8">
    <div class="table-responsive">
	<table class="table table-bordered table-striped">
	    <colgroup>
		<col class="col-xs-8">
	    </colgroup>
	    <div class="bs-example">
		<table class="table">
		    <!-- Show form info -->
		    <h4><?php echo $report[0]['unit_id'] . ' - ' . $report[0]['name'] . ' - ' . $report[0]['year'];?></h4>
		    <h3>Modifying Report for Plan <?php echo $report[0]['plan_id'] ?></h3>
		    <div class="controls">
			<div class="panel-group" id="accordion">
			    <div class="panel panel-success">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
					   Outcomes
					</a>
				    </h4>
				</div>
				<div class="panel-body">
				    <?php $ctr = 0;?>
				    <!-- Show outcome/assessment text -->
				    <?php foreach($descriptions as $description) : ?>
					<?php $ctr++;?>
					 <?php echo($ctr); ?>.<?php echo $description;?>
					 					 
					</br>
					
					<?php endforeach; ?>
				</div>
			    
			<!-- Other database fields -->
			<div class="panel panel-success">
			    <div class="panel-heading">
			      <h4 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
				   Population assessed
				</a>
			      </h4>
			    </div>
			    <div id="collapseThree" class="panel-collapse collapse">
			      <div class="panel-body">
				<?php
				    $elem = $form->get('population');
				    $elem->setValue($report[0]['population']);
				    echo $this->formRow($elem);
				?>	 
					
			      </div>
			    </div>
      
			    <div class="panel-heading">
				<h4 class="panel-title">
				  <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
				     Results
				  </a>
				</h4>
			     </div>
			    <div id="collapseFour" class="panel-collapse collapse">
				<div class="panel-body">
				<?php
				    $elem = $form->get('results');
				    $elem->setValue($report[0]['results']);
				    echo $this->formRow($elem);
				?>	 
				</div>
			    </div>
			    <div class="panel-heading">
				<h4 class="panel-title">
				  <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
				     Conclusions
				  </a>
				</h4>
			    </div>
			    <div id="collapseFive" class="panel-collapse collapse">
			       <div class="panel-body">
				<?php
				    $elem = $form->get('conclusions');
				    $elem->setValue($report[0]['conclusions']);
				    echo $this->formRow($elem);
				?>	 
				</div>
			    </div>
			    
			    <div class="panel-heading">
				<h4 class="panel-title">
				  <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
				     Actions
				  </a>
				</h4>
			    </div>
			    <div id="collapseSix" class="panel-collapse collapse">
			       <div class="panel-body">
				<?php
				    $elem = $form->get('actions');
				    $elem->setValue($report[0]['actions']);
				    echo $this->formRow($elem);
				?>	 
			       </div>
			    </div>
			 
			</div>
		    </div>
		</div>
		    <table>
			<!-- Show existing documents -->
			<?php
			    if(count($documents) > 0){ ?>
			    <th>File</th><th>&nbsp&nbspDescription</th><td>&nbsp&nbsp</td>
			<?php
				foreach($documents as $doc){
			?>
			<tr><td><a href="<?php echo $this->url('id',
				array('action'=>'download',
			       'id' => $doc['id'],
			       ));
			?>"><?php echo $doc['file_name']; ?></a></td><td>
			<?php echo '&nbsp&nbsp' . $doc['file_description']; ?>
			    </br></td><td><input type="checkbox" name="delete[]" value="<?php echo $doc['id'];?>">&nbsp&nbspDelete<br>
			    </td></tr>
			<?php
				}
			    }
			?>
		    </table>
		<table>
		    
		    <!-- Add new documents, allows 2 new -->
		    <th>Add Files</th>
		
		    <tr><td>File Description</td></tr>
		    
		    <tr>
			<td>
			    <?php echo $this->formInput($form->get('fileDescription0')); ?>
			</td>
			<td>
			    <?php echo $this->formFile($form->get('fileUpload0')); ?>
			</td>
		
			<td>
			  <a href="#" id="removeFile0" name="removeFile0"  onclick="$('#fileUpload').replaceWith($('#fileUpload').clone());document.getElementById('fileDescription0').value = '';">Remove File</a>
		        </td>
		    </tr>
		    <tr>
			<td>
			    <?php echo $this->formInput($form->get('fileDescription1')); ?>
			</td>
			<td>
			    <?php echo $this->formFile($form->get('fileUpload1')); ?>
			</td>
		
			<td>
			  <a href="#" id="removeFile1" name="removeFile1"  onclick="$('#fileUpload1').replaceWith($('#fileUpload1').clone());document.getElementById('fileDescription1').value = '';">Remove File</a>
	 	        </td>
		</table>
		</br>
	    </div> <!-- controls -->
	    <input class="btn btn-success btn-md" onclick="" id="submitButton" value="Submit Changes"></input>

		<?php
		// onclick jquery functions appear in index.phtml
		    if($report[0]['draft_flag'] == 1){
		    ?>
		       <input class="btn btn-primary btn-md" onclick="" id="draftButton" value="Save Draft"></input>
	   
		    <?php
		   }
		   if($role == 1 || $role == 2){  // admin and chairs can delete
		      if ($report[0]['draft_flag'] == 1){ // drafts are completely deleted
		   ?>
		       <input class="btn btn-warning btn-md pull-right" onclick="" id="deleteDraft" value="Delete Draft"></input>
		    <?php
		      }
		      else{// submitted reports are set to inactive
		    ?>
			 <input class="btn btn-warning btn-md pull-right" onclick="" id="deleteButton" value="Delete Report"></input>
		   <?php
		      }
		   }
		?>
	    </table>
	</table>
	<!-- Close form -->
    <?php echo $this->form()->closeTag();?>
  </div><!-- /example -->
    <?php
	}
    ?>