
<?php
if(!$results){
    echo 'There are no reports associated with this plan';
}else{
    $form->setAttribute('action', $this->url('reports', array('action' => 'updateReport')));
    $form->setAttribute('name', 'data');
    $form->setAttribute('id', 'data');
    $form->setAttribute('enctype', 'multipart/form-data');

    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id')->setAttribute('value', $report[0]['id']));
    echo $this->formHidden($form->get('status')->setAttribute('value', '0'));
?>

<div class="col-md-8">
    <div class="table-responsive">
	<table class="table table-bordered table-striped">
	    <colgroup>
		<col class="col-xs-8">
	    </colgroup>  
            <dl>
        
                        <dt><h3>Enter Feedback For Report Shown Below</h3>
                            Choose Feedback Option    
                        </dt>
                        <dd>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                           <?php
                                $feedbackFlag = $report[0]['feedback'];
                                $elem = $form->get('feedbackFlag');
                                $elem->setValue($feedbackFlag);
                                $this->formRadio()->setSeparator('</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;');
                                echo $this->formRadio($elem);
                             ?>
                        </dd>
                        </br>
                        <dt>Enter Feedback Message</dt>
                        <dd>
                            <?php
                                $elem = $form->get('feedbackText');
                                $elem->setValue($report[0]['feedback_text']);
                                echo $this->formTextarea($elem);
                            ?>						
                        </dd>
                    </dl>
                    <input class="btn btn-success btn-md noprint" onclick="" id="submitButton" value="Submit"></input>

                    </br>
                    </br>	
		      
               <div class="bs-example">
		<table class="table">
		    <h4><?php echo $report[0]['unit_id'] . ' - ' . $report[0]['name'] . ' - ' . $report[0]['year'];?></h4>
		    <div class="controls">
			<div class="panel-group" id="accordion">
			    <!-- Show meta or outcomes -->
			    <div class="panel panel-success">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<?php
					if($report[0]['meta_flag'] == 0){
					    $type = 'Outcomes';
					}else{
					    $type = 'Meta Description';
					}
					
					?>
					<?php echo $type;?>
				    </h4>
				</div>
				<div class="panel-body">
				
				    <?php
				    $ctr = 1;
				    foreach($descriptions as $description) : 
					echo($ctr) . '. ' . $description . '</br>';
					$ctr++;
				    endforeach;
				    ?>
			       
				</div>
			    </div>
			    <div class="panel panel-success">
				<!-- Database fields -->
				<div class="panel-heading">
				    <h4 class="panel-title">
					Population Assessed
				    </h4>
				</div>
				<div class="panel-body">
					<?php echo $report[0]['population']?>
				</div>
			    </div>
			    <div class="panel panel-success">
				<div class="panel-heading">
				    <h4 class="panel-title">
					Results
				    </h4>
				</div>
				<div class="panel-body">
				    <?php echo $report[0]['results']?>
				</div>
			     </div>
			     <div class="panel panel-success">
				<div class="panel-heading">
				    <h4 class="panel-title">
				    Conclusion
				    </h4>
				</div>
				<div class="panel-body">
					<?php echo $report[0]['conclusions']?>
				</div>
			    </div>
			    <div class="panel panel-success">
				<div class="panel-heading">
				    <h4 class="panel-title">
					Actions
				    </h4>
				</div>
				<div class="panel-body">
					<?php echo $report[0]['actions']?>
				</div>
			    </div>
			
			</div>
			<table>
			    <!-- Show existing documents -->
			    <?php
				if(count($documents) > 0){
				    echo '<th>File</th><th>&nbsp&nbspDescription</th>';
			  	    foreach($documents as $doc){
			    ?>
			    <tr><td><a href="<?php echo $this->url('id',
				    array('action'=>'download',
				   'id' => $doc['id'],
				   ));
				    ?>"><?php echo $doc['file_name']; ?></a></td><td>
				    <?php echo '&nbsp&nbsp' . $doc['file_description']; ?>
				    </td></tr>
				    <?php
				    }
				}
				else{
				    echo 'No Documents Attached';
				}
			    ?>
			</table>
	    </br>
	</div> <!-- controls -->
	<button type="button" class="btn btn-primary noprint" style="width:100px" onclick="printPage()">Print</button>&nbsp;
    </table>
</table>
<?php
 
}
?>


