
<?php
// If there aren't results, tell user
if(!$results){
    echo '</br></br></br></br>There are no plans that match your criteria';
}else{
   echo '<h4><center>Plans for ' . $title. '</center></h4>';
		
?>

<div class="col-md-8">
    <div class="panel-group" id="accordion">
	<!-- Loop through returned plans -->
	<?php
	    $ctr = 0;
	    foreach($plans as $plan) :
		$ctr++; 
	?>
	<div class="panel panel-success">
	    <div class="panel-heading">
		<h4 class="title">
		<?php echo "Plan # " . $plan->id; 
		    if ($plan->metaFlag == 1){
			echo " &nbsp; Meta Assessment Plan";
		    }
		    else{
			echo " &nbsp; Outcomes Plan";
		    }
		
		    $showButton = 1;
		    if ($action=="View" || $action== "Provide Feedback")
		    {
		        if ($plan->hasReport != 2){ // no submitted report exists
			    echo " <span class='pull-right'>Report Does Not Exist</span>";
			    $showButton = 0;
			}
		    }
		    else if($action == "Add")
		    {
		        if ($plan->hasReport == 1)  // draft exists
			{
			    echo " <span class='pull-right'>Report Draft Already Exists</span>";
			    $showButton = 0;
			}
			else if ($plan->hasReport == 2) // submitted report already exists
			{
			     echo " <span class='pull-right'>Report Already Exists</span>";
			     $showButton = 0;
			}
		    }
		    else // modify action
		    {
			if ($plan->hasReport == 0){
			    echo " <span class='pull-right'>Report Does Not Exist</span>";
			    $showButton = 0;
			}
		    }
		    if ($showButton == 1){	
		?>	    <input class="btn btn-primary btn-sm pull-right"
			 	    onclick="getReports('<?php echo $action;?>', <?php echo $plan->id; ?>);"
				    id="<?php echo $action . '" value="' . $action . ' &raquo"';?>"
			    </input>
		<?php
		    }
		?>
		</h4>
	    </div>
		<!-- Show outcomes or assessment text for each plan -->
	    <div class="panel-body">
		<table class="table">
		    <?php
		    
		    $oCtr = 0; 
		    foreach($plan->descriptions as $text) : 
			$oCtr++;
		    ?>
		    <tr>
			<th><?php echo($oCtr); ?>.</th>
			<td><?php echo $text;?></td>
		    </tr>
		    <?php endforeach; ?>
		</table>
		    
	    </div><!-- close body-->
	</div><!-- close panel-success-->

	<?php
	    endforeach;}
	?>
    </div><!-- close panel-group-->
</div><!-- close column-->

