
<?php
if(!$results){
    echo 'There are no reports associated with this plan';
}else{
?>
<div class="col-md-8">
    <div class="table-responsive">
	<table class="table table-bordered table-striped">
	    <colgroup>
		<col class="col-xs-8">
	    </colgroup>  
	    <div class="bs-example">
		<table class="table">
		    <h4><?php echo $report[0]['unit_id'] . ' - ' . $report[0]['name'] . ' - ' . $report[0]['year'];?></h4>
		    <div class="controls">
		      <h3>Showing Report for Plan <?php echo $report[0]['plan_id'] ?></h3>
		 	<div class="panel-group" id="accordion">
			    <!-- Show meta or outcomes -->
			    <div class="panel panel-success">
				<div class="panel-heading">
				    <h4 class="panel-title">
					<?php
					if($report[0]['meta_flag'] == 0){
					    $type = 'Outcomes';
					}else{
					    $type = 'Meta Description';
					}
					
					?>
					<?php echo $type;?>
				    </h4>
				</div>
				<div class="panel-body">
				
				    <?php
				    $ctr = 1;
				    foreach($descriptions as $description) : 
					echo($ctr) . '. ' . $description . '</br>';
					$ctr++;
				    endforeach;
				    ?>
			       
				</div>
			    </div>
			    <div class="panel panel-success">
				<!-- Database fields -->
				<div class="panel-heading">
				    <h4 class="panel-title">
					Population Assessed
				    </h4>
				</div>
				<div class="panel-body">
					<?php echo $report[0]['population']?>
				</div>
			    </div>
			    <div class="panel panel-success">
				<div class="panel-heading">
				    <h4 class="panel-title">
					Results
				    </h4>
				</div>
				<div class="panel-body">
				    <?php echo $report[0]['results']?>
				</div>
			     </div>
			     <div class="panel panel-success">
				<div class="panel-heading">
				    <h4 class="panel-title">
				    Conclusion
				    </h4>
				</div>
				<div class="panel-body">
					<?php echo $report[0]['conclusions']?>
				</div>
			    </div>
			    <div class="panel panel-success">
				<div class="panel-heading">
				    <h4 class="panel-title">
					Actions
				    </h4>
				</div>
				<div class="panel-body">
					<?php echo $report[0]['actions']?>
				</div>
			    </div>
			     <?php
				// general users may not see feedback
				if ($role != 0)
				{
			    ?>
				<div class="panel panel-success">
				    <div class="panel-heading">
					<!-- Feedback flag -->
					<h4 class="panel-title">
					    Feedback
					    <?php
						if($report[0]['feedback'] == 2){
						    echo '&nbsp &nbsp (Approved)';
						}else if($report[0]['feedback'] == 1){
						    echo '&nbsp &nbsp (In need of revision)';
						}
					    ?>
					</h4>
				    </div>
				    <div class="panel-body">
					    <?php echo $report[0]['feedback_text']?>
				    </div>
				</div>
				<?php
				}
				?>
			</div>
			<table>
			    <!-- Show existing documents -->
			    <?php
				if(count($documents) > 0){
				    echo '<th>File</th><th>&nbsp&nbspDescription</th>';
			  	    foreach($documents as $doc){
			    ?>
			    <tr><td><a href="<?php echo $this->url('id',
				    array('action'=>'download',
				   'id' => $doc['id'],
				   ));
				    ?>"><?php echo $doc['file_name']; ?></a></td><td>
				    <?php echo '&nbsp&nbsp' . $doc['file_description']; ?>
				    </td></tr>
				    <?php
				    }
				}
				else{
				    echo 'No Documents Attached';
				}
			    ?>
			</table>
	    </br>
	</div> <!-- controls -->
	<button type="button" class="btn btn-primary noprint" style="width:100px" onclick="printPage()">Print</button>&nbsp;
    </table>
</table>
<?php
 
}
?>


