
<?php
// If there aren't results, tell user
if(!$results){
    echo '</br></br></br></br>There are no plans that match your criteria';
}else{

?>

<div class="col-md-8">
    <div class="panel-group" id="accordion">
	<!-- Loop through returned plans -->
	<?php
	    $ctr = 0;
	    foreach($plans as $plan) :

		$ctr++; 
		
	?>
	<div class="panel panel-success">
	    <div class="panel-heading">
		<h4 class="title">
		<?php echo "Plan # " . $ctr; ?>
	        <input class="btn btn-primary btn-sm" onclick="getReports('<?php echo $action;?>', <?php echo $plan->id; ?>);" id="<?php echo $action;?>" value="<?php echo $action;?>  &raquo"></input>
		    
		</h4>
	    </div>
		<!-- Show outcomes or assessment text for each plan -->
	    <div class="panel-body">
		<table class="table">
		    <?php
		    $oCtr = 0; 
		    foreach($plan->descriptions as $text) : 
			$oCtr++;
		    ?>
		    <tr>
			<th><?php echo($oCtr); ?>.</th>
			<td><?php echo $text;?></td>
		    </tr>
		    <?php endforeach; ?>
		</table>
		    
	    </div><!-- close body-->
	</div><!-- close panel-success-->

	<?php
	    endforeach;}
	?>
    </div><!-- close panel-group-->
</div><!-- close column-->

