<!-- partial file to display results of query 1 -->

    <caption><h4><?php echo $querytitle; ?></h4>
             <h5><?php echo '(' . $totalDisplayed . ' missing, ' . ($totalPrograms-$totalDisplayed) .
                            ' out of ' . $totalPrograms . ' submitted)'; ?></h5>
    </caption>
    <tr>
         <th>Division</th>
         <th>Department</th>
         <th>Program</th>
    </tr>
    <?php
        if ($programs==''){ ?>
            <tr>
            <td><?php echo "No records found."; ?></td>
            <td></td>
            <td></td>
            </tr>
        <?php
        }
        else{
            foreach ($programs as $program) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($program['division']);?></td>
                <td><?php echo $this->escapeHtml($program['unit_id']);?></td>
                <td><?php echo $this->escapeHtml($program['name']);?></td>
            </tr>
            <?php endforeach; }?>
       
 