<?php echo $this->partial('admin/admin/menu.phtml',array('active'=>'query')); ?>
<?php
$title = 'Queries';
$this->headTitle($title);
?>
<style type="text/css">
dd {
 font-weight: bold;
 padding-left: 2em;
}
</style>
<div id='topofpage'><center><h3>Administrator Queries</h3></center></div>
<div class = "panel panel-default">
    <div class="panel-body">
    
    <div class='col-md-4 noprint'>
        <!-- Choose Query -->
        <dl>
            <dt>Query 1:
            </dt>
            <dd>
            Show programs missing plans.
            <!-- Choose Years -->
            <select class="selectpicker" id="q1year" name="q1year" data-style="btn-primary" title='Choose Year'>
               <option data-hidden="true"></option>
            </select>
            </dd>
        </dl>
        <dl>
            <dt>Query 2:
            </dt>
            <dd>
            Show programs missing reports.
             <!-- Choose Years -->
            <select class="selectpicker" id="q2year" name="q2year" data-style="btn-primary" title='Choose Year'>
               <option data-hidden="true"></option>
            </select>
            </dd>
        </dl>
        <dl>
            <dt>Query 3:
            </dt>
            <dd>
            Show programs conducting meta assessment.
            <!-- Choose Years -->
            <select class="selectpicker" id="q3year" name="q3year" data-style="btn-primary" title='Choose Year'>
               <option data-hidden="true"></option>
            </select>
             </dd>
        </dl>
        <dl>
            <dt>Query 4:
            </dt>
            <dd>
            Show programs requesting funding.
            <!-- Choose Years -->
            <select class="selectpicker" id="q4year" name="q4year" data-style="btn-primary" title='Choose Year'>
               <option data-hidden="true"></option>
            </select>
          </dd>
        </dl>
        <dl>
            <dt>Query 5:
            </dt>
            <dd>
            Show programs that have modified their outcomes since (<i>enter date</i>) 
             <input type="text" class="span2" id="dp5">
             <button type="button" class="btn-primary" id="query5">Go</button>
            </dd>
        </dl>
        <dl>
            <dt>Query 6:
            </dt>
            <dd>Show programs that have added or modified last year's plan.
            <button type="button" class="btn-primary" id="query6">Go</button>
            </dd>
        </dl>
        <dl>
            <dt>Query 7:
            </dt>
            <dd>
            Show programs that have added or modified last year's report.
            <button type="button" class="btn-primary" id="query7">Go</button>
            
            </dd>
        </dl>
        <dl>
            <dt>Query 8:
            </dt>
            <dd>
            Show plans/reports needing feedback.
            <!-- Choose Years -->
            <select class="selectpicker" id="q8year" name="q8year" data-style="btn-primary" title='Choose Year'>
               <option data-hidden="true"></option>
            </select>
          </dd>
        </dl>
        <dl>
            <dt>Query 9:
            </dt>
            <dd>
             Show programs that changed their assessors since (<i>enter date</i>) 
             <input type="text" class="span2" id="dp9">
             <button type="button" class="btn-primary" id="query9">Go</button>
            </dd>
        </dl>
        <dl>
            <dt>Query 10:
            </dt>
            <dd>
             Show programs that are missing learning outcomes.
             <button type="button" class="btn-primary" id="query10">Go</button>
            </dd>
        </dl> 
    </div><!--close column-->


    <!--column 2 - this holds the partial-->
    <div class="col-md-8">
        <!-- create a print button -->
	<button id="printbutton" type="button" class="btn btn-primary noprint pull-right" onclick="printPage()">Print &raquo;</button>&nbsp;  <!--window.print()-->
	<div class="table-responsive">
            <table class="table table-bordered table-striped" id="resultsTable" name="resultsTable">
            </table>
        </div> <!-- end of table-responsive -->
        		  
    </div> <!-- end of col-md-8--> 
  </div>
</div>




<script>

$(document).ready(function () {
    
    // set years for year dropdowns
    var currentYear = new Date().getFullYear();
    // startyear for dropdowns set in session namespace variables
    var startYear = <?php echo $startYear ?>;
	    
    // create the list of years the user can select
    // identify today's date and adjust to the current school year
    // 2013 - 2014 is from July 2013 - June 2014
    // 2012 - 2013 is from July 2012 - June 2013
    // repeat until startyear
	    
    // get today's data
    var today = new Date();
    
    // identify the month and year
    var month= today.getMonth() + 1; //January is 0
    var year = today.getFullYear(); // yyyy
   
    // if the current month is Jan - June the current year is correct
    // if the current month is July - Dec then current year needs to be incremented by 1
    if (month >= 7 && month <= 12) {
	year++;
    }
	    
    // set the complete number of years to display in the year selector 
    var yearsToDisplay = year - startYear + 1; // add one since the last entry needs to be the (year before the low year) to the (low year)

    var resetyear = year;
    $('#q1year').append('<option  data-hidden="true"></option>');
    for (var i = 0; i < yearsToDisplay; i++){	    
        $('#q1year').append('<option value = ' + year + '>' + (year-1) + ' - ' + year + '</option>');
        year--;
    }
    $('#q1year').selectpicker('refresh');
   
    year = resetyear;
    $('#q2year').append('<option  data-hidden="true"></option>');
    for (var i = 0; i < yearsToDisplay; i++){	    
        $('#q2year').append('<option value = ' + year + '>' + (year-1) + ' - ' + year + '</option>');
        year--;
    }
    $('#q2year').selectpicker('refresh');
    
    year = resetyear;
    $('#q3year').append('<option  data-hidden="true"></option>');
    for (var i = 0; i < yearsToDisplay; i++){	    
        $('#q3year').append('<option value = ' + year + '>' + (year-1) + ' - ' + year + '</option>');
        year--;
    }
    $('#q3year').selectpicker('refresh');
    
    year = resetyear;
    $('#q4year').append('<option  data-hidden="true"></option>');
    for (var i = 0; i < yearsToDisplay; i++){	    
        $('#q4year').append('<option value = ' + year + '>' + (year-1) + ' - ' + year + '</option>');
        year--;
    }
    $('#q4year').selectpicker('refresh');
 
    $('#dp5').datepicker({
	format: 'mm-dd-yyyy',
        date:''
    });
    
    year = resetyear;
    $('#q8year').append('<option  data-hidden="true"></option>');
    for (var i = 0; i < yearsToDisplay; i++){	    
        $('#q8year').append('<option value = ' + year + '>' + (year-1) + ' - ' + year + '</option>');
        year--;
    }
    $('#q8year').selectpicker('refresh');

     $('#dp9').datepicker({
	format: 'mm-dd-yyyy',
        date:''
    });
    
    $('#printbutton').hide();
})


$(document).on('change', '#q1year', function () {
    // clear rhs of page
    $('#resultsTable').html("");

    // get dropdown value
    var year = $('#q1year option:selected').val();
    
    // reset all drop downs
    resetDropDowns();
    
    // put value selected back so displays in dropdown after clearing
    $('select[name=q1year]').val(year);
    $('.selectpicker').selectpicker('refresh');
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery1')); ?>";
    urlform = urlform + '/' + year;
    ajaxCall(urlform);
    
});


$(document).on('change', '#q2year', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // get user entered year
    var year = $('#q2year option:selected').val();
    
    // reset all drop downs
    resetDropDowns();
    
    // put value selected back so displays in dropdown after clearing
    $('select[name=q2year]').val(year);
    $('.selectpicker').selectpicker('refresh');
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery2')); ?>";
    urlform = urlform + '/' + year;
    ajaxCall(urlform);
  
});

$(document).on('change', '#q3year', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // get user entered year
    var year = $('#q3year option:selected').val();
    
    // reset all drop downs
    resetDropDowns();
    
    // put value selected back so displays in dropdown after clearing
    $('select[name=q3year]').val(year);
    $('.selectpicker').selectpicker('refresh');
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery3')); ?>";
    urlform = urlform + '/' + year;
    ajaxCall(urlform);
  
});

$(document).on('change', '#q4year', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // get user entered year
    var year = $('#q4year option:selected').val();
    
    // reset all drop downs
    resetDropDowns();
    
    // put value selected back so displays in dropdown after clearing
    $('select[name=q4year]').val(year);
    $('.selectpicker').selectpicker('refresh');
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery4')); ?>";
    urlform = urlform + '/' + year;
    ajaxCall(urlform);
  
});

$(document).on('click', '#query5', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // get date from datepicker
    var date = $('#dp5').val();
    
    // reset all drop downs
    resetDropDowns();
    
    // put value selected back so displays in dropdown after clearing
    $('#dp5').val(date);
    
    // replace all dashes to send via URL
    date = date.replace(/-/g, '');
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery5')); ?>";
    urlform = urlform + '/' + date;
    ajaxCall(urlform);
});

$(document).on('click', '#query6', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // reset all drop downs
    resetDropDowns();
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery6')); ?>";
    ajaxCall(urlform);
});

$(document).on('click', '#query7', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // reset all drop downs
    resetDropDowns();
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery7')); ?>";
    ajaxCall(urlform);
});


$(document).on('change', '#q8year', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // get user entered year
    var year = $('#q8year option:selected').val();
    
    // reset all drop downs
    resetDropDowns();
    
    // put value selected back so displays in dropdown after clearing
    $('select[name=q8year]').val(year);
    $('.selectpicker').selectpicker('refresh');
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery8')); ?>";
    urlform = urlform + '/' + year;
    ajaxCall(urlform);
  
});

$(document).on('click', '#query9', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // get date from datepicker
    var date = $('#dp9').val();
    
    // reset all drop downs
    resetDropDowns();
    
    // put value selected back so displays in dropdown after clearing
    $('#dp9').val(date);
    
    // replace all dashes to send via URL
    date = date.replace(/-/g, '');
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery9')); ?>";
    urlform = urlform + '/' + date;
    ajaxCall(urlform);
});

$(document).on('click', '#query10', function () {
    // clear rhs of page
    $('#resultsTable').html("");
    
    // reset all drop downs
    resetDropDowns();
    
    // create url for redirect url(route, array(controller, action))
    var urlform = "<?php echo $this->url('query', array('controller'=>'queries', 'action'=>'getQuery10')); ?>";
    ajaxCall(urlform);
});

function ajaxCall(urlform){
            // asynchronous ajax code to populate program/degree selector
        $.ajax({
          url: urlform,
          type: "GET",
          // dataType returned from server
          dataType: "html",
          error : function(xhr, status, error) {
             console.log("ERROR: ", xhr, xhr.status, xhr.getAllResponseHeaders());
          },
          success: function(results){
            // clear any existing html in the partial div
            $('#resultsTable').html("");
            $('#resultsTable').html(results);
            $('#printbutton').show();
        },
       });
}

function resetDropDowns(){
    // reset dropdowns except dropdown matching parameter
    $('select[name=q1year]').val(1);
    $('select[name=q2year]').val(1);
    $('select[name=q3year]').val(1);
    $('select[name=q4year]').val(1);
    $('select[name=q8year]').val(1);
    $('#dp5').val('');
    $('#dp9').val('');
    //$('html, body').animate((
    //scrollTop: $("#topofpage").offset().top}, 0);
    
    $(window).scrollTop($("#topofpage").offset().top);
    $('.selectpicker').selectpicker('refresh');
}

/**
 * Only print specific elements on the view page.  To mark elements as non printable
 * add class noprint
 */

function printPage()
{
    $('.noprint').hide();
    window.print();
    $('.noprint').show();
}   
</script>

