<?php echo $this->partial('admin/admin/menu.phtml',array('active'=>'admin')); ?>
<?php
$title = 'Administration Menu';
$this->headTitle($title);
?>
<div class="row admin-home">
    
    <div class="title col-md-4">
    </div>
    <div class="title col-md-4">
        <center><h3><?php echo $this->escapeHtml($title); ?></h3></center>
        </br>
        <dl>
            <dt><h4>Manage Users
              <a role="button" class="btn btn-primary btn-sm pull-right" href="<?php echo $this->url('user');?>">Select</a>
            </h4></dt>
            </br>
            <dt><h4>Manage Programs
              <a role="button" class="btn btn-primary btn-sm pull-right" href="<?php echo $this->url('program');?>">Select</a>
            </h4></dt>
            </br>
            <dt><h4>Run Queries
              <a role="button" class="btn btn-primary btn-sm pull-right" href="<?php echo $this->url('query');?>">Select</a>
            </h4></dt>
        </dl>
        
    </div>
</div>
