<?php echo $this->partial('admin/admin/menu.phtml',array('active'=>'admin')); ?>
<?php
$title = 'Administration Menu';
$this->headTitle($title);
?>
<div class="row admin-home">
    <div class="title col-md-12">
        <center><h2><?php echo $this->escapeHtml($title); ?></h2></center>
        <center>
            <h3>Manage Users
              <a role="button" class="btn btn-primary btn-md" href="<?php echo $this->url('user');?>">Go</a>
            </h3>
            <h3>Manage Programs
              <a role="button" class="btn btn-primary btn-md" href="<?php echo $this->url('program');?>">Go</a>
            </h3>
            <h3>Run Queries
              <a role="button" class="btn btn-primary btn-md" href="<?php echo $this->url('query');?>">Go</a>
            </h3>
        </center>
    </div>
</div>
