<?php
$form = $unitform;
$form->setAttribute('action', $this->url('program', array('action' => 'addunit')));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="control-group col-md-12">  
    <div class="control-group">  
      <div class="form-group">
        <?php echo $this->formLabel($form->get('division')->setLabelAttributes(array('class'=>'control-label'))); ?>
        <?php echo $this->formSelect($form->get('division')); ?>
    </div>
    <div class="form-group">
        <?php
            echo $this->formLabel($form->get('unit_id')->setLabelAttributes(array('class'=>'control-label'))); 
            echo '<p>(3 letters only)</p>';
            echo $this->formInput($form->get('unit_id')); ?>
    </div>
    </div>
   
    <div class="form-group">
        <?php echo $this->formSubmit($form->get('unitsubmit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>