<?php
$title = 'Manage Programs';
$this->headTitle($title);
?>
<?php echo $this->partial('admin/admin/menu.phtml',array('active'=>'program')); ?>
<div class="col-md-12">
    <center><h2><?php echo $this->escapeHtml($title); ?></h2></center>
</div>

<div class="col-md-2 program-form-wrapper">
    <h3>Add New Unit</h3>
    <div class="program-form" style="overflow:hidden;">
        <?php echo $this->partial('admin/program/addunit.phtml',array('unitform'=>$this->unitform));?>
    </div>
</div>
<div class="col-md-3 program-form-wrapper">
    <h3>Add New Program</h3>
    <div class="program-form" style="overflow:hidden;">
        <?php echo $this->partial('admin/program/addprogram.phtml',array('programform'=>$this->programform));?>
    </div>
</div>

<div class="col-md-7">
    <h3>Modify Existing Programs</h3>
    <div class="table-responsive">
            <colgroup>
                <col class="col-xs-8">
            </colgroup>
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Division</th>
                            <th>Unit Name</th>
                            <th>Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->paginator as $program) : ?>
                        <tr class="active">
                                    <td><?php echo $this->escapeHtml($program->id);?></td>
                                    <td><?php echo $this->escapeHtml($program->division);?></td>
                                    <td><?php echo $this->escapeHtml($program->unit_id);?></td>
                                    <td><?php echo $this->escapeHtml($program->name);?></td>
                                    <td>
                                        <a class="btn btn-primary btn-xs"
                                           href="<?php echo $this->url('program',
                                                                        array('action'=>'edit',
                                                                        'id' => $program->id));?>">
                                            <?php echo $this->translate ('Edit') ?> &raquo;
                                        </a>
                                        
                                        <a class="btn btn-warning btn-xs"
                                           onclick="if (confirm('Are you sure you want to delete the program <?php echo $program->name;?>?')) { document.location = this.href; } return false;"
                                           href="<?php echo $this->url('program',
                                                 array('action'=>'delete', 'id' => $program->id));?>"><?php echo $this->translate ('Delete') ?> &raquo;</a>
                                    </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>

                </table>
                <?php // add at the end of the file after the table
                    echo $this->paginationControl(
                            $this->paginator,// the paginator object
                            'sliding',// the scrolling style; 
                            //see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                            array('admin/program/controls.phtml', 'Program'),// the partial to use to render the control
                            array( 'route' => 'program')// the route to link to when a user clicks a control link
                            );
                    ?>
    </div>
</div>

