<?php

    $title = 'Assessment Meta Plan';
    $this->headTitle($title);
    
    // Init Form
    $form = $this->form;
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('enctype', 'multipart/form-data');
    $form->setAttribute('action', $this->url('plans',array('action'=>'insertmeta')));
    $form->prepare();
?>	

    <!-- create the right side of the page -->
    <div class="container">
	<center><h3>Assessment Plans - Add Meta Assessment Plan</h3></center>
        <p></p>
	
	<!-- begin creating the form -->
	<?php echo $this->form()->openTag($form); ?>
	    <div class="row">
		<p></p>
		<!-- create header line -->
		<?php	
		    // create a string out of the programs array to use as a hidden element to pass between the pages
		    $allPrograms = "";
		    if (!empty($this->programs)) {
			foreach ($this->programs as $program) :
			    $allPrograms = $allPrograms . $program . ", ";
			endforeach;
			
			// remove the last ", " added on after the last loop above
			$allPrograms = substr($allPrograms, 0, -2);
		    }
		    echo "<h4>" . $this->unit . ": " . $allPrograms . ": " . $this->year . "</h4>";
		    
		    // prepare hidden elements to pass data between pages	
		    $elem = $form->get('action');
		    $elem->setValue($action);					    
		    echo $this->formInput($elem);
	    
		    $elem = $form->get('unit');
		    $elem->setValue($unit);					    
		    echo $this->formInput($elem);
	    
		    $elem = $form->get('programs');
		    $elem->setValue($allPrograms);					    
		    echo $this->formInput($elem);
		    
		    $elem = $form->get('year');
		    $elem->setValue($year);					    
		    echo $this->formInput($elem);
		?>
		<!-- create meta assessment block -->
		<div class="col-md-8">
		    <div class="controls">
			<h4>Describe the Meta Assessment Plan & Rationale</h4>
			<p></p>
			    
			    <?php
				$elem = $form->get('textMetaDescription');
				echo $this->formTextarea($elem);
			    ?>
			
	    		<!-- use partials to load the upload buttons -->
			<?php echo $this->partial('plans/plans/plansuploadbuttonpartial.phtml', array('form' => $form,)); ?>
    
			<!-- add the save draft and submit buttons -->
			<?php
			    
			    $elem = $form->get('formSavePlan');
			    $elem->setName('formSubmitPlan');
			    echo $this->formButton($elem);

			    $elem = $form->get('formSubmitPlan');
			    echo $this->formButton($elem);
			?>
		    </div>
		</div>
	    </div>
	<?php echo $this->form()->closeTag($form); ?>	
    </div>