<?php
    $title = 'Add Modify Assessment Plan';
    $this->headTitle($title);

?>

<?php
    // Init Form
    $form = $this->form;
    $form->setAttribute('enctype', 'multipart/form-data');
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('action', $this->url('plans',array('action'=>'updatePlan')));
    $form->prepare();
?>

<!-- create the right side of the page -->
<div class="container">
    <center><h3>Assessment Plans - Modify Specific Plan</h3></center>
    <p></p>  
    <div class="row">
	<p></p>

	<!-- Begin creating the form -->
	<?php echo $this->form()->openTag($form); ?>
	    
	<div class="col-md-8">
	    <div class="bs-example">
		<!-- create header line -->
		<?php
		    $allPrograms = "";
		    if (!empty($programs)) {
			foreach ($programs as $program) :
			    $allPrograms = $allPrograms . $program . ", ";
			endforeach;
			
			// remove the last ", " added on after the last loop above
			$allPrograms = substr($allPrograms, 0, -2);
		    }
		    echo "<h4>" . $unit . ": " . $allPrograms . ": " . $year . "</h4>";
			    
		    // prepare hidden elements to pass data between pages		
		    $elem = $form->get('planId');
		    $elem->setValue($planId);					    
		    echo $this->formInput($elem);
		    
		    $elem = $form->get('unit');
		    $elem->setValue($unit);					    
		    echo $this->formInput($elem);
    
		    $elem = $form->get('programs');
		    $elem->setValue($allPrograms);					    
		    echo $this->formInput($elem);
		    
		    $elem = $form->get('year');
		    $elem->setValue($year);					    
		    echo $this->formInput($elem);
		    
		    $elem = $form->get('dbDraftFlag');
		    $elem->setValue($plan['draft_flag']);					    
		    echo $this->formInput($elem);
		?>
		<div class="controls">
		    <h3>Modifying Plan <?php echo $planId; ?></h3>
                    
		    <div class="panel-group" id="accordion">

		    <!-- if not meta plan then display outcomes -->
		    <?php
			if ($plan['meta_flag'] == 0)
			{
		    ?>
			<div class="panel panel-success">
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOutcome">Outcomes</a>
				</h4>
			    </div>
			    <div id="collapseOutcome" class="panel-collapse collapse in">
				<div class="panel-body">
				    <?php							    
					    // loop through all the outcomes
					    $outcomeCount = 0;
					    foreach ($outcomes as $outcome) :
						if ($outcomeCount == 0){
						    $prevTitle = $outcome->getProgramName();
						    echo $outcome->getProgramName(); 
						}
						if ($prevTitle != $outcome->getProgramName()){
						    $prevTitle = $outcome->getProgramName();
						    echo $outcome->getProgramName(); 
						}
						$outcomeCount++;
						// create each outcome check box
    				 	  	if ($outcome->getType() === '0'){
						    // outcome is not currently in plan - leave checkbox empty
					?>
						    <p><input validate="true" type="checkbox" id="checkboxOutcomes<?php echo $outcomeCount ?>"
						     name="checkboxOutcomes<?php echo $outcomeCount ?>">
					<?php		
					   	}
						else{
						    // outcome currently in plan - mark check box
					?>
						    <p><input validate="true" type="checkbox" id="checkboxOutcomes<?php echo $outcomeCount ?>"
						     name="checkboxOutcomes<?php echo $outcomeCount ?>" checked>
					<?php		
					   	}
					?>
					       <!-- create hidden id for each checkbox - used in modify to handle toggle of checkboxes -->
	    				       <input type="hidden" name="checkboxOutcomesID<?php echo $outcomeCount ?>"
								    id="checkboxOutcomesID<?php echo $outcomeCount ?>"
								    value="<?php echo $outcome->getOutcomeId() ?>">
		
					      <!-- add the counter with the outcome text to the row -->
					      <?php echo $outcomeCount; ?>. <?php echo $outcome->getOutcomeText() ?></td>
  	      				   </p>
					<?php
					    endforeach;
					           
					?>
	      		            <input type="hidden" name="outcomeCount" id="outcomeCount" value="<?php echo $outcomeCount ?>">

				</div>
			    </div>
			</div>
    
			<div class="panel panel-success">
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapseAssessmentMethod">
					Assessment Method
				    </a>
				</h4>
			    </div>
    
			    <div id="collapseAssessmentMethod" class="panel-collapse collapse">
				<div class="panel-body">
				    <?php
					$elem = $form->get('textAssessmentMethod');
					$elem->setValue($plan['assessment_method']);
					echo $this->formTextarea($elem);
				    ?>
				</div>
			    </div>
    
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapsePopulation">
					Population Assessed
				    </a>
				</h4>
			    </div>
    
			    <div id="collapsePopulation" class="panel-collapse collapse">
				<div class="panel-body">
				    <?php
					$elem = $form->get('textPopulation');
					$elem->setValue($plan['population']);
					echo $this->formTextarea($elem);
				    ?>						
				</div>
			    </div>
    
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapseSampleSize">
					Sample Size Assessed
				    </a>
				</h4>
			    </div>
    
			    <div id="collapseSampleSize" class="panel-collapse collapse">
				<div class="panel-body">
				    <?php
					$elem = $form->get('textSamplesize');
					$elem->setValue($plan['sample_size']);
					echo $this->formTextarea($elem);
				    ?>						
				</div>
			    </div>
    
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapseAssessmentDate">
					Assessment Date
				    </a>
				</h4>
			    </div>
    
			    <div id="collapseAssessmentDate" class="panel-collapse collapse">
				<div class="panel-body">
				    <?php
					$elem = $form->get('textAssessmentDate');
					$elem->setValue($plan['assessment_date']);
					echo $this->formTextarea($elem);
				    ?>						
				</div>
			    </div>
    
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapseCost">
					Cost of Assessment 
				    </a>
				</h4>
			    </div>
    
			    <div id="collapseCost" class="panel-collapse collapse">
				<div class="panel-body">
				    <?php
					$elem = $form->get('textCost');
					$elem->setValue($plan['cost']);
					echo $this->formTextarea($elem);
				    ?>						
				</div>
			    </div>
			    
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapseFundingFlag">
					Funding Requested
				    </a>
				</h4>
			    </div>
    
			    <div id="collapseFundingFlag" class="panel-collapse collapse">
				<div class="panel-body">
				    <?php
					$fundingFlag = $plan['funding_flag'];
					$elem = $form->get('fundingFlag');
					$elem->setValue($fundingFlag);
					echo $this->formRow($form->get('fundingFlag'));
    
					echo "<br>";
					echo "<a href=\"http://northcentralcollege.edu/home/\" target=\"_blank\" >Funding Form</a>";
				    ?>						
				</div>
			    </div>		
    
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapseAnalysisType">
				    Type of Analysis
				    </a>
				</h4>
			    </div>
    
			    <div id="collapseAnalysisType" class="panel-collapse collapse">
				<div class="panel-body">
				    <?php
					$elem = $form->get('textAnalysisType');
					$elem->setValue($plan['analysis_type']);
					echo $this->formTextarea($elem);
				    ?>						
				</div>
			    </div>
    
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapseAdministrator">
				     Administrator
				    </a>
				</h4>
			    </div>
    
			    <div id="collapseAdministrator" class="panel-collapse collapse">
				<div class="panel-body">
				    <?php
					$elem = $form->get('textAdministrator');
					$elem->setValue($plan['administrator']);
					echo $this->formTextarea($elem);
				    ?>						
				</div>
			    </div>
    
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapseAnalysisMethod">
					 Analysis Method
				    </a>
				</h4>
			    </div>
    
			    <div id="collapseAnalysisMethod" class="panel-collapse collapse">
				<div class="panel-body">
				    <?php
					$elem = $form->get('textAnalysisMethod');
					$elem->setValue($plan['analysis_method']);
					echo $this->formTextarea($elem);
				    ?>						
				</div>
			    </div>
    
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapseScope">
					Scope of Assessment
				    </a>
				</h4>
			    </div>
    
			    <div id="collapseScope" class="panel-collapse collapse">
				<div class="panel-body">
				    <?php
					$elem = $form->get('textScope');
					$elem->setValue($plan['scope']);
					echo $this->formTextarea($elem);
				    ?>						
				</div>
			    </div>					    
				
			</div>
		    <?php
			}
			else
			{
		    ?>
			<!-- If there are no outcomes then display all the meta database attributes -->
			<div class="panel panel-success">
			    <div class="panel-heading">
				<h4 class="panel-title">
				    <a data-toggle="collapse" data-parent="#accordion" href="#collapseMetaDescription">
					Meta Description.
				    </a>
				</h4>
			    </div>

			    <div class="panel-body">
				    <?php
					$elem = $form->get('textMetaDescription');
					$elem->setValue($plan['meta_description']);
					echo $this->formTextarea($elem);
				    ?>	
				
			    </div>
			</div>
		    <?php
			}
		    ?>
		    
		    </div>
		</div> <!-- controls -->    

		<!-- display all the plan document information -->
		<div id="contentModify">
		    <div>
			<?php
			    // loop through all the plan documents
			    $planDocumentsCount = 0;
			    if (!empty($planDocuments)) {
				foreach ($planDocuments as $planDocument) :
				    $planDocumentsCount++;
				    
				    // combine the file name and file ext
				    $filename = $planDocument['file_name'] . "." . $planDocument['file_ext'];
			?>						    					
				<p>
				    <!-- Create a delete button  -->
				    <a class="btn btn-warning btn-xs" id="deleteDocument" name="deleteDocument" value="<?php echo $planDocument['id'];?>"> 
					Delete &raquo;
				    </a>
				    &nbsp;
				    &nbsp;
				    
				    <!-- display the plan document information -->
				    <?php echo $planDocumentsCount;?>.
				    
				    <!-- create a hyperlink and url to display the document in another pgae -->
				    <a  href="<?php echo $this->url('plans',
							 array('action'=>'downloadFile',
							       'id' => $planDocument['id'],
							       ));
					  ?>"
				    >
					<?php echo $filename?>
				    </a>
				    <?php echo " Description: ". $planDocument['file_description']?>
				</p>
			<?php
				endforeach;
			    }
			?>
		    </div>
		</div>		

		<!-- use partials to load the upload buttons -->
		<?php echo $this->partial('plans/plans/plans-upload-button-partial.phtml', array('form' => $form,)); ?>
		
		<!-- display the save draft and submit buttons -->
		<?php
		    // Only display the save draft button if the plan is currently set as a draft in the database once the plan is submitted it can no longer be modified as a draft
		    if($plan['draft_flag'] == "1"){
			$elem = $form->get('formSavePlan');
			$elem->setName('formSubmitPlan');
			echo $this->formButton($elem);
		    }

		    $elem = $form->get('formSubmitPlan');
		    echo $this->formButton($elem);
		?>
	    </div>
	</div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>