<?php
    $title = 'View Assessment Plan';
    $this->headTitle($title);
?>

<?php
    // Init Form
    $form = $this->form;
    $form->setAttribute('class', 'form-horizontal');
    $form->prepare();
?>

<!-- create the right side of the page -->
<div class="container">
    <center><h3>Assessment Plans - View Specific Plan</h3></center>
   
    <p></p>  
    <div class="row">

	<p></p>
	<div class="col-md-8">
	    <div class="table-responsive">
		<table class="table table-bordered table-striped">
		    <colgroup><col class="col-xs-8"></colgroup>
		    <div class="bs-example">
			<table class="table">
			    <!-- create header line -->
			    <?php
			        $allPrograms = "";
				if (!empty($programs)) {
				    foreach ($programs as $program) :
					$allPrograms = $allPrograms . $program . ", ";
				    endforeach;
				    
				    // remove the last ", " added on after the last loop above
				    $allPrograms = substr($allPrograms, 0, -2);
				}
				echo "<h4>" . $unit . ": " . $allPrograms . ": " . $year . "</h4>";
			    ?>
			     
			    <div class="controls">
				<h3>Showing Plan <?php echo $planId; ?></h3>
                    
				<!-- begin creating the accordion -->
				<div class="panel-group" id="accordion">
				    
				    <!-- create the outcome display -->
				    <?php
					if (!empty($outcomes)) {
				    ?>				    
					    <div class="panel panel-success">
						<div class="panel-heading">
						    <h4 class="panel-title">
							Outcomes
						    </h4>
						</div>
	
						<div class="panel-body">
						    <?php
							// loop through all the outcomes
							$outcomeCount = 0;
								foreach ($outcomes as $outcome) :
								    $outcomeCount++;
						    ?>
								    <!-- display the outcome information -->
								    <p><?php echo $outcomeCount;?>. <?php echo $outcome->getOutcomeText() ?></p>
						    <?php
								endforeach;
						    ?>
						</div>
					    </div>
    
					    <!-- all the database attributes are listed below -->
					    <div class="panel panel-success">
						<div class="panel-heading">
						    <h4 class="panel-title">
						        Assessment Method
						    </h4>
						</div>
	    
						<div class="panel-body">
						    <?php
							$elem = $form->get('textAreaViewOnly');
							$elem->setValue($plan['assessment_method']);
							echo $this->formTextarea($elem);
						    ?>
						</div>
					    </div>
	    
					    <div class="panel panel-success">
						<div class="panel-heading">
						    <h4 class="panel-title">
						    Population Assessed
						    </h4>
						</div>
	
						<div class="panel-body">
						    <?php
							$elem = $form->get('textAreaViewOnly');
							$elem->setValue($plan['population']);
							echo $this->formTextarea($elem);
						    ?>
						</div>
					    </div>    
					
					    <div class="panel panel-success">
						<div class="panel-heading">
						    <h4 class="panel-title">
						    Sample Size Assessed
						    </h4>
						</div>
						<div class="panel-body">
							<?php
							    $elem = $form->get('textAreaViewOnly');
							    $elem->setValue($plan['sample_size']);
							    echo $this->formTextarea($elem);
							?>
						    </div>
						</div>
					    </div>
					    <div class="panel panel-success">
						<div class="panel-heading">
						    <h4 class="panel-title">
						    Assessment Date
						    </h4>
						</div>
	    
						<div class="panel-body">
						    <?php
							$elem = $form->get('textAreaViewOnly');
							$elem->setValue($plan['assessment_date']);
							echo $this->formTextarea($elem);
						    ?>
						</div>
					    </div>
					    <div class="panel panel-success">
						<div class="panel-heading">
						    <h4 class="panel-title">
						    Cost of Assessment 
						    </h4>
						</div>
					        <div class="panel-body">
						    <?php
							$elem = $form->get('textAreaViewOnly');
							$elem->setValue($plan['cost']);
							echo $this->formTextarea($elem);
						    ?>
					        </div>
					    </div>
					    <div class="panel panel-success">	
						<div class="panel-heading">
						    <h4 class="panel-title">
						    Funding Requested
						    </h4>
						</div>
	    
						<div class="panel-body">
						    <?php
							$fundingFlag = $plan['funding_flag'];
							$label = "No";
							if ($fundingFlag == 1) {
							    $label = "Yes";
							}
							
							$elem = $form->get('textAreaViewOnly');
							$elem->setValue($label);
							echo $this->formTextarea($elem);
						    ?>
						</div>
					    </div>
					    <div class="panel panel-success"> 
						<div class="panel-heading">
						    <h4 class="panel-title">
						    Type of Analysis
						    </h4>
						</div>
	    
						<div class="panel-body">
						    <?php
							$elem = $form->get('textAreaViewOnly');
							$elem->setValue($plan['analysis_type']);
							echo $this->formTextarea($elem);
						    ?>
						</div>
					    </div>
					    <div class="panel panel-success">	
						<div class="panel-heading">
						    <h4 class="panel-title">
						    Administrator
						    </h4>
						</div>
						<div class="panel-body">
						    <?php
							$elem = $form->get('textAreaViewOnly');
							$elem->setValue($plan['administrator']);
							echo $this->formTextarea($elem);
						    ?>
						</div>
					    </div>
					    <div class="panel panel-success">	    
						<div class="panel-heading">
						    <h4 class="panel-title">
						    Analysis Method
						    </h4>
						</div>
						<div class="panel-body">
						    <?php
							$elem = $form->get('textAreaViewOnly');
							$elem->setValue($plan['analysis_method']);
							echo $this->formTextarea($elem);
						    ?>
						</div>
					    </div>
					    <div class="panel panel-success">	    
						<div class="panel-heading">
						    <h4 class="panel-title">
							Scope of Assessment
						    </h4>
						</div>
						<div class="panel-body">
						    <?php
							$elem = $form->get('textAreaViewOnly');
							$elem->setValue($plan['scope']);
							echo $this->formTextarea($elem);
						    ?>
						</div>
					    </div>					    
							
				    <?php
					}
					else
					{
				    ?>
					    <div class="panel panel-success">
					    <!-- all the meta database attributes are listed below -->
					    <div class="panel-heading">
						<h4 class="panel-title">
						Meta Description
						</h4>
					    </div>
	
					    <div class="panel-body">
						<?php
						    $elem = $form->get('textAreaViewOnly');
						    $elem->setValue($plan['meta_description']);
						    echo $this->formTextarea($elem);
						?>	
					    </div>
					</div>
				    <?php
					}
				    ?>
		   	            <?php
					// general users may not see feedback
					if ($role != 0)
					{
				    ?>
				     
				    <!-- display all the feedback attributes -->
					<div class="panel panel-success">
					    <div class="panel-heading">
						<h4 class="panel-title">
						Feedback
						<?php
						    $feedbackFlag = $plan['feedback'];
						    if ($feedbackFlag == 1) {
							echo " &nbsp &nbsp  (In Need of Revision)";
						    } else if ($feedbackFlag == 2){
							echo " &nbsp &nbsp (Ready to be Carried Out)";
						    }
						?>    
						</h4>
					    </div>
		    
					    <div class="panel-body">
						<?php
						    $elem = $form->get('textAreaViewOnly');
						    $elem->setValue($plan['feedback_text']);
						    echo $this ->formTextarea($elem);
						?>						
					    </div>
					</div>
		    
					<?php
					}
					?>
					</div>
				    </div>
			    </div> <!-- controls -->

			    <!-- display all the plan documents and set them to no print -->
			    <div class='noprint'>
				<div>
				    <?php
				   	// loop through all the plan documents
					$planDocumentsCount = 0;
					if (!empty($planDocuments)) {
					    foreach ($planDocuments as $planDocument) :
						$planDocumentsCount++;
						
						// combine the file name and file ext
						$filename = $planDocument['file_name'] . "." . $planDocument['file_ext'];
						
						//get the id
						$id = $planDocument['id']
				    ?>
						<!-- display the plan document information -->
						<p><?php echo $planDocumentsCount;?>.
						
						<a  href="<?php echo $this->url('plans',
										 array('action'=>'downloadFile',
										'id' => $id,
										));
							  ?>"
						>
						<?php echo $filename ?></a>
						<?php echo "  Description: ". $planDocument['file_description']?></p>
				    <?php
					    endforeach;
					}
					else{
					   echo "<p>No Documents Attached</p>";
					}
				    ?>
				</div>
				
				<!-- create a print button -->
				<button type="button" class="btn btn-primary noprint" onclick="printPage()">Print &raquo;</button>  <!--window.print()-->
			    </div>
			</table>
		    </div>
		</table>
	    </div>
	</div>
    </div>
</div>
