<?php

$title = 'Academic Assessment Portal';
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<br>
<br><br><br>
<center>
    <h3>Please make a selection</h3><br>
    <?php
        echo $this->form()->openTag($form);
        foreach($form as $element){
          echo $this->formElement($element);
          echo "&nbsp &nbsp &nbsp";
        }
        echo $this->form()->closeTag($form);
       
    ?>
</center>