<?php

$title = 'Academic Assessment Login';
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>

<center>
    
    <h3>Please log in with your NCC User ID and Password</h3>
    <br><br>
    
    <?php
        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        echo $this->form()->closeTag($form);
    ?>
    <h4><?php echo $this->message; ?></h4>
    
</center>